baseURL = "https://staging.d1hcc03ui9os06.amplifyapp.com/"
# baseURL = "https://main.dj1h7qwffogh3.amplifyapp.com/"
languageCode = "en-us"
title = "where is pete now???"
#title = "Hugo-Amplify Test (default)"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
menu = ['main', 'footer']
#theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
#googleAnalytics = ""

[params]
  author = "fastrkr"
  description = "where friends can share"
  #githubUsername = "#"
  accent = "light-blue"
  showBorder = true
  backgroundColor = "yellow"
  font = "Roboto Mono"
  #font = "Raleway" # should match the name on Google Fonts!
  highlight = true
  highlightStyle = "dark"
  highlightLanguages = ["go", "yaml", "bash"]
  copyright = "© fastrkr, 2022. Powered by [Hugo](https://gohugo.io) and the Ananke theme. GDPR Compliant; no tracking enabled."
  version = "0.0.3"
  #featured_image = "static/images/gohugo-default-hero-image-raw.jpg"
  recent_posts_number = 2

[[menu.main]]
  url = "/"
  name = "Home"
  weight = 1

[[menu.main]]
  url = "/about/"
  name = "About"
  weight = 2

[[menu.main]]
  url = "/post/"
  name = "Posts"
  weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
  url = "mailto:info@example.com"
  name = "fas fa-envelope"
  weight = 1

[[menu.icon]]
  url = "https://github.com/seanrmurphy/hugu-amplify-test"
  name = "fab fa-github"
  weight = 2

[[menu.icon]]
  url = "https://twitter.com/seanrmurphy/"
  name = "fab fa-twitter"
  weight = 3

[[menu.icon]]
  url = "https://www.linkedin.com/in/seanrmurphy1"
  name = "fab fa-linkedin"
  weight = 4

[module]

[[module.imports]]
  path = "github.com/calintat/minimal"

# GDPR related
[privacy]

[privacy.disqus]
  disable = true

[privacy.googleAnalytics]
  disable = true

[privacy.instagram]
  disable = true

[privacy.twitter]
  disable = true

[privacy.vimeo]
  disable = true

[privacy.youtube]
  disable = true

