baseURL = "http://3.210.176.183/"
languageCode = "en-us"
title = "where is pete now?"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
menu = ['main', 'footer'
footer = "copyright(c) 2021 go4wd.consulting"

resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "where is pete now?"
    weight = 1
    contentDir = "content/en"
  [languages.fr]
    title = "Ou sois mon ami Pierre?"
    weight = 2
    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.8
  filename = "sitemap.xml"

[params]
  author = ""
  favicon = ""
  site_logo = ""
  description = "where old friends go, good times are bount to follow!"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-orange"
  featured_image = "/images/gohugo-default-hero-image-raw.jpg"
  recent_posts_number = 2

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/gvhconnect"
